name: Deploy to Qiniu

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Set up Qshell
        run: |
          wget https://github.com/qiniu/qshell/releases/download/v2.16.1/qshell-v2.16.1-linux-amd64.tar.gz
          tar -xzf qshell-v2.16.1-linux-amd64.tar.gz
          mv qshell-v2.16.1-linux-amd64/qshell /usr/local/bin/qshell

      - name: Upload to Qiniu
        run: |
          qshell account ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }} myaccount
          qshell qupload2 --src-dir=./build --bucket=djz-note
